app/models.py
from app import db

class Relation(db.Model):
    recette_id = db.Column(db.ForeignKey('recette.id'), primary_key=True)
    ingredient_id = db.Column(db.ForeignKey('ingredient.id'), primary_key=True)
    qte_necessaire = db.Column(db.Integer)
    qte_achat = db.Column(db.Integer)
    recette = db.relationship("Recette", back_populates="ingredients")
    ingredient = db.relationship("Ingredient", back_populates="recettes")

    def set_qte_necessaire(self, qte) :
        self.qte = qte

    def set_qte_achat(self) :
        qte_achat = self.ingredient.qte
        qte_necessaire = self.qte_necessaire
        while qte_achat < qte_necessaire :
            qte_achat += self.ingredient.qte
        self.qte_achat = qte_achat


class Ingredient(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), index=True, unique=True)
    cost = db.Column(db.Integer, index=True, default=0)
    unite = db.Column(db.String(64), index=True)
    qte = db.Column(db.Integer)
    recettes = db.relationship("Relation", back_populates="ingredient")

    def set_cost(self, cost):
        self.cost = cost

    def set_qte(self, qte):
        self.qte = qte

class Recette(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(64), index=True, unique=True)
    cost = db.Column(db.Integer, index=True)
    ingredients = db.relationship("Relation", back_populates="recette")

    def set_cost(self) :
        cost = 0
        for ingredient in self.ingredients :
            cost += (ingredient.qte_achat/ingredient.ingredient.qte)*ingredient.ingredient.cost
        self.cost = cost


'''
class Semaine(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    numero = db.Column(db.Integer, index=True)
    jours = db.relationship('Jour', backref='jour', lazy='dynamic')

class Jour(db.Model):
    id = db.Column(db.Integeer, primary_key = True)
    midi = db.Column('')
    soir = db.Column('')
'''

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FloatField, IntegerField
from wtforms.validators import ValidationError, DataRequired

class AddIngredientForm(FlaskForm):
    name = StringField('Nom', validators = [DataRequired()])
    cost = FloatField('Coût',default=0.0)
    submit = SubmitField('Ajouter')

class AddRecetteForm(FlaskForm):
    name = StringField('Nom', validators = [DataRequired()])
    ingredients = StringField("Ingrédients")
    submit = SubmitField("Terminer la recette")

app/__init__.py
import os
from flask import Flask
from config import Config
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

db = SQLAlchemy()
migrate = Migrate()
bootstrap= Bootstrap()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)



    bootstrap.init_app(app)
    db.init_app(app)
    migrate.init_app(app, db)

    from app.main import bp as main_bp

    app.register_blueprint(main_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main',__name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import render_template, url_for, redirect, flash

from app.main.forms import AddRecetteForm, AddIngredientForm

@bp.route('/', methods=['GET','POST'])
@bp.route('/index', methods=['GET','POST'])
def index():
    return render_template('index.html')

@bp.route('/recettes')
def recettes():
    return render_template('recettes.html')

@bp.route('/recette/<recettename>')
def edit_recette(recettename):
    return render_template('recette.html')

@bp.route('/recette/newrecette', methods=['GET','POST'])
def add_recette():
    form = AddRecetteForm()
    if form.validate_on_submit():
        flash('Recette ajoutée !')
        return redirect(url_for('main.index'))
    return render_template('recette.html',form=form)

@bp.route('/planning')
def modify_planning():
    return render_template('planning.html')

@bp.route("/ingredient/newingredient", methods=['GET','POST'])
def add_ingredient():
    form = AddIngredientForm()
    if form.validate_on_submit():
        flash('Ingrédient ajouté !')
        return redirect(url_for('main.index'))
    return render_template('ingredient.html', form=form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {{ ('Bienvenue') }}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Planning</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.modify_planning') }}">{{ 'Planning' }}</a></li>
                    <li><a href="{{ url_for('main.recettes') }}">{{ 'Recettes' }}</a></li>
                    <li><a href="{{ url_for('main.add_recette') }}">{{ 'Ajouter une recette' }}</a></li>
                    <li><a href="{{ url_for('main.add_ingredient') }}">{{ 'Ajouter un ingrédient' }}</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    {{ super() }}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Repas</th>
      <th scope="col">Lundi</th>
      <th scope="col">Mardi</th>
      <th scope="col">Mercredi</th>
      <th scope="col">Jeudi</th>
      <th scope="col">Vendredi</th>
      <th scope="col">Samedi</th>
      <th scope="col">Dimanche</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">Midi</th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <th scope="row">Soir</th>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Ingrédients</th>
      <th scope="col">Stock</th>
    </tr>
  </thead>
  {% if ingredients %}
  <tbody>
    {% for ingredient in ingredients %}
    <tr>
        <th scope="row">{{ ingredient.getName() }}</th>
        <td>{{ ingredient.getStock() }}</td>
    </tr>
    {% endfor %}
  </tbody>
  {% endif %}
</table>
{% endblock %}

app/templates/ingredient.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Ajouter un ingrédient</h1>
    <div class="row">
        <div class="col-md-4">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/planning.html
{% extends "base.html" %}

app/templates/recette.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Ajouter une recette</h1>
    <div class="row">
         <div class="col-md-4">
-            {{ wtf.quick_form(form) }}
-        </div>
    </div>
{% endblock %}

app/templates/recettes.html
{% extends "base.html" %}